parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    
    App\OpenApi\JwtDecorator:
        decorates: 'api_platform.openapi.factory'
        arguments: ['@.inner']
    
    App\Controller\RegisterController\:
        resource: '../src/Controller/RegisterController.php'
        tags: ['controller.service_arguments']

    App\State\UserPasswordHasher:
            bind:
                $processor: '@api_platform.doctrine.orm.state.persist_processor'
